
import React from 'react';
import { X, FileDiff, Download, Sparkles, Loader2 } from 'lucide-react';
import { ExtractedDocument, SchemaField } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { diffWords } from 'diff';
import { generateComparisonSummary } from '../services/geminiService';

interface ComparisonModalProps {
  documents: ExtractedDocument[];
  schema: SchemaField[];
  onClose: () => void;
}

const ComparisonModal: React.FC<ComparisonModalProps> = ({ documents, schema, onClose }) => {
  const [aiSummary, setAiSummary] = React.useState<string>('');
  const [loadingSummary, setLoadingSummary] = React.useState<boolean>(true);

  React.useEffect(() => {
    let mounted = true;
    const fetchSummary = async () => {
      try {
        const summary = await generateComparisonSummary(documents);
        if (mounted) setAiSummary(summary);
      } catch (e) {
        console.error("Error generating comparison:", e);
        if (mounted) setAiSummary("Unable to generate AI comparison summary at this time.");
      } finally {
        if (mounted) setLoadingSummary(false);
      }
    };
    
    if (documents.length > 0) {
      fetchSummary();
    }
    
    return () => { mounted = false; };
  }, [documents]);

  const handleExportPDF = () => {
    const doc = new jsPDF('l'); // landscape
    
    doc.setFontSize(18);
    doc.text("Document Comparison Report", 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated by DocuGrid AI - ${new Date().toLocaleDateString()}`, 14, 28);
    
    // Add summary to PDF if available
    if (aiSummary) {
        // Strip markdown asterisks for PDF export
        const cleanSummary = aiSummary.replace(/\*\*/g, '');
        const splitSummary = doc.splitTextToSize(cleanSummary, 270);
        doc.text(splitSummary, 14, 35);
    }

    const startY = aiSummary ? 80 : 35;

    const head = [['Field', ...documents.map(d => d.fileName)]];
    const body = [
      ['Risk Level', ...documents.map(d => d.risk.level)],
      ...schema.map(field => [
        field.label,
        ...documents.map(d => d.data[field.key]?.value || '—')
      ])
    ];

    autoTable(doc, {
      startY: startY,
      head: head,
      body: body,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [59, 130, 246] }
    });

    doc.save('comparison_report.pdf');
  };

  const renderDiffCell = (baseValue: string, currentValue: string) => {
    // If exact match, simple render
    if (baseValue === currentValue) {
      return <span className="text-slate-800 dark:text-slate-200">{currentValue}</span>;
    }

    // Calculate Diff
    // We use diffWords to keep it readable for sentences and names
    const diff = diffWords(baseValue, currentValue);

    return (
      <span className="leading-relaxed break-words">
        {diff.map((part, i) => {
          // If removed (exists in base, not in current), we don't show it in the current cell
          // to keep the cell reading as the current document's actual content.
          if (part.removed) return null;

          // If added (exists in current, not in base), it's a difference/addition.
          // If neither, it's common text.
          return (
            <span 
              key={i} 
              className={part.added 
                ? "bg-amber-200 dark:bg-amber-600/40 text-slate-900 dark:text-white px-1 rounded box-decoration-clone font-medium border-b-2 border-amber-400 dark:border-amber-500" 
                : "text-slate-800 dark:text-slate-300 opacity-90"
              }
              title={part.added ? "Difference from base document" : undefined}
            >
              {part.value}
            </span>
          );
        })}
      </span>
    );
  };

  const formatText = (text: string) => {
    const parts = text.split(/(\*\*.*?\*\*)/);
    return parts.map((part, idx) => {
        if (part.startsWith('**') && part.endsWith('**')) {
            return <strong key={idx} className="font-semibold text-slate-900 dark:text-white">{part.slice(2, -2)}</strong>;
        }
        return part;
    });
  };

  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-slate-900 w-full max-w-6xl max-h-[90vh] rounded-2xl shadow-2xl flex flex-col border border-slate-200 dark:border-slate-800 animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 rounded-t-2xl">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-brand-100 dark:bg-brand-900/20 rounded-lg text-brand-600">
               <FileDiff className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">Compare Documents</h2>
              <p className="text-sm text-slate-500">Comparing {documents.length} selected documents against Base</p>
            </div>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={handleExportPDF}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-700 dark:text-slate-200 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors shadow-sm"
            >
              <Download className="w-4 h-4" /> Export Report
            </button>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-full transition-colors text-slate-500"
            >
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto custom-scrollbar p-6 bg-slate-50/50 dark:bg-slate-900">
          
          {/* AI Summary Section */}
          <div className="mb-6 bg-white dark:bg-slate-950 rounded-xl p-5 shadow-sm border border-slate-200 dark:border-slate-800 relative overflow-hidden ring-1 ring-slate-100 dark:ring-slate-800">
              <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-brand-400 to-indigo-500"></div>
              <div className="flex items-start gap-4">
                  <div className="p-2.5 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl text-indigo-600 dark:text-indigo-400 mt-0.5 shadow-sm border border-indigo-100 dark:border-indigo-900/50">
                      {loadingSummary ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
                  </div>
                  <div className="flex-1">
                      <h3 className="text-sm font-bold uppercase tracking-wide text-indigo-600 dark:text-indigo-400 mb-2 flex items-center gap-2">
                          AI Comparison Analysis
                          {!loadingSummary && <span className="text-[10px] bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300 px-2 py-0.5 rounded-full">Generated by Gemini</span>}
                      </h3>
                      {loadingSummary ? (
                          <div className="space-y-3 animate-pulse opacity-60">
                              <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-3/4"></div>
                              <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-full"></div>
                              <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-5/6"></div>
                          </div>
                      ) : (
                          <div className="prose prose-sm dark:prose-invert max-w-none text-slate-700 dark:text-slate-300">
                               {aiSummary.split('\n').map((line, i) => {
                                  const isHeader = (line.trim().match(/^\d+\./));
                                  return (
                                    <p key={i} className={`mb-1.5 leading-relaxed ${isHeader ? 'font-bold text-slate-800 dark:text-slate-100 mt-3 mb-2' : ''}`}>
                                        {formatText(line)}
                                    </p>
                                  )
                               })}
                          </div>
                      )}
                  </div>
              </div>
          </div>

          <table className="w-full border-collapse border-spacing-0 shadow-sm rounded-lg overflow-hidden">
            <thead>
              <tr className="bg-white dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
                <th className="p-4 text-left min-w-[200px] sticky top-0 bg-white dark:bg-slate-950 z-10 shadow-sm">
                  <span className="text-xs font-bold uppercase text-slate-400 tracking-wider">Field</span>
                </th>
                {documents.map((doc, index) => (
                  <th key={doc.id} className="p-4 text-left min-w-[250px] sticky top-0 bg-white dark:bg-slate-950 z-10 shadow-sm border-l border-slate-100 dark:border-slate-800">
                    <div className="flex items-center gap-2">
                      {index === 0 ? (
                        <span className="bg-brand-100 text-brand-700 dark:bg-brand-900/50 dark:text-brand-300 text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wide ring-1 ring-brand-200 dark:ring-brand-800">
                          Base
                        </span>
                      ) : (
                        <span className="bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400 text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wide">
                          Comparison
                        </span>
                      )}
                    </div>
                    <div className="font-bold text-slate-900 dark:text-white truncate max-w-[200px] mt-2 text-sm" title={doc.fileName}>
                      {doc.fileName}
                    </div>
                    <div className={`mt-1 inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold border ${
                      doc.risk.level === 'HIGH' ? 'bg-red-50 text-red-700 border-red-100 dark:bg-red-900/20 dark:text-red-300 dark:border-red-900/50' :
                      doc.risk.level === 'MEDIUM' ? 'bg-amber-50 text-amber-700 border-amber-100 dark:bg-amber-900/20 dark:text-amber-300 dark:border-amber-900/50' :
                      'bg-green-50 text-green-700 border-green-100 dark:bg-green-900/20 dark:text-green-300 dark:border-green-900/50'
                    }`}>
                      {doc.risk.level} RISK
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800 bg-white dark:bg-slate-900">
              {schema.map(field => {
                 const baseValue = documents[0].data[field.key]?.value || '';
                 
                 // Check if row has differences to highlight row background slightly
                 const values = documents.map(d => d.data[field.key]?.value);
                 const isRowDiff = new Set(values).size > 1;

                 return (
                  <tr key={field.key} className={`group hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors ${isRowDiff ? 'bg-slate-50/30 dark:bg-slate-900/40' : ''}`}>
                    <td className="p-4 align-top bg-white dark:bg-slate-900 group-hover:bg-slate-50 dark:group-hover:bg-slate-800/50 transition-colors border-r border-slate-100 dark:border-slate-800">
                      <div className="font-semibold text-sm text-slate-700 dark:text-slate-300">{field.label}</div>
                      {field.description && (
                        <div className="text-xs text-slate-400 mt-1 leading-tight">{field.description}</div>
                      )}
                    </td>
                    {documents.map((doc, index) => {
                      const currentValue = doc.data[field.key]?.value || '';
                      
                      return (
                        <td key={`${doc.id}-${field.key}`} className={`p-4 align-top text-sm border-l border-slate-100 dark:border-slate-800 ${
                          index > 0 && isRowDiff ? 'bg-amber-50/10 dark:bg-amber-900/5' : ''
                        }`}>
                          {index === 0 ? (
                            <span className="text-slate-800 dark:text-slate-200">{currentValue}</span>
                          ) : (
                            renderDiffCell(baseValue, currentValue)
                          )}
                        </td>
                      );
                    })}
                  </tr>
                 );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ComparisonModal;
